/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.AetherVoyages.view;

/**
 *
 * @author ggpin
 */
public class PromoNational extends javax.swing.JInternalFrame {

    /**
     * Creates new form PromoNational
     */
    public PromoNational() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackground = new javax.swing.JPanel();
        jsBackground = new javax.swing.JScrollPane();
        jpJS = new javax.swing.JPanel();
        jpPromoNational = new javax.swing.JPanel();
        jpTabs = new javax.swing.JPanel();
        jSep = new javax.swing.JSeparator();
        lblAetherVoyages = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setTitle("Aether Voyages - Promo National");

        jpBackground.setBackground(new java.awt.Color(255, 255, 255));
        jpBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jsBackground.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jpPromoNational.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpPromoNationalLayout = new javax.swing.GroupLayout(jpPromoNational);
        jpPromoNational.setLayout(jpPromoNationalLayout);
        jpPromoNationalLayout.setHorizontalGroup(
            jpPromoNationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );
        jpPromoNationalLayout.setVerticalGroup(
            jpPromoNationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpJSLayout = new javax.swing.GroupLayout(jpJS);
        jpJS.setLayout(jpJSLayout);
        jpJSLayout.setHorizontalGroup(
            jpJSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpJSLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpPromoNational, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpJSLayout.setVerticalGroup(
            jpJSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPromoNational, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jsBackground.setViewportView(jpJS);

        javax.swing.GroupLayout jpBackgroundLayout = new javax.swing.GroupLayout(jpBackground);
        jpBackground.setLayout(jpBackgroundLayout);
        jpBackgroundLayout.setHorizontalGroup(
            jpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        jpBackgroundLayout.setVerticalGroup(
            jpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsBackground)
        );

        jpTabs.setBackground(new java.awt.Color(0, 51, 204));
        jpTabs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSep.setForeground(new java.awt.Color(255, 255, 255));

        lblAetherVoyages.setFont(new java.awt.Font("PMingLiU-ExtB", 3, 24)); // NOI18N
        lblAetherVoyages.setText("Aether Voyages");

        javax.swing.GroupLayout jpTabsLayout = new javax.swing.GroupLayout(jpTabs);
        jpTabs.setLayout(jpTabsLayout);
        jpTabsLayout.setHorizontalGroup(
            jpTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSep)
            .addGroup(jpTabsLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lblAetherVoyages)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpTabsLayout.setVerticalGroup(
            jpTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTabsLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblAetherVoyages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSep;
    private javax.swing.JPanel jpBackground;
    private javax.swing.JPanel jpJS;
    private javax.swing.JPanel jpPromoNational;
    private javax.swing.JPanel jpTabs;
    private javax.swing.JScrollPane jsBackground;
    private javax.swing.JLabel lblAetherVoyages;
    // End of variables declaration//GEN-END:variables
}
